arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [en, hi, fr, ar, te, gu]
use-deferred-loading: false
flutter:
  generate: true 